refactor: use twine for releases

diff --git a/release b/release
--- a/release
+++ b/release
@@ -31,6 +31,11 @@ command -v rst-lint > /dev/null || {
     exit 1
 }
 
+command -v twine > /dev/null || {
+    echo -e "${RED}WARNING: Missing twine binary, please run: pip install twine==3.2.0${COLOR_OFF}\n"
+    exit 1
+}
+
 if [[ "$@" != "major" ]] && [[ "$@" != "minor" ]] && [[ "$@" != "patch" ]]; then
     echo -e "${RED}WARNING: Invalid release type, must specify 'major', 'minor', or 'patch'${COLOR_OFF}\n"
     exit 1
@@ -125,7 +130,8 @@ git push -q origin master && git push -q --tags
 if [[ "$PUBLIC" == "true" ]]; then
     echo -e "${YELLOW}--->${COLOR_OFF} Creating python release"
     cp README.rst README
-    python setup.py sdist bdist_wheel upload > /dev/null
+    python setup.py sdist bdist_wheel > /dev/null
+    twine upload dist/*
     rm README
 fi
 
